<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>PixivUtil.WindowsTrial</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\PixivUtil2.exe" Condition="Exists('Resources\PixivUtil2.exe')" />
  </ItemGroup>
</Project>
